const q1 = document.querySelector(".question1")
const q2 = document.querySelector(".question2")
const q3 = document.querySelector(".question3")
const q4 = document.querySelector(".question4")
const q5 = document.querySelector(".question5")
const a1 = document.querySelector(".answer1")
const a2 = document.querySelector(".answer2")
const a3 = document.querySelector(".answer3")
const a4 = document.querySelector(".answer4")
const a5 = document.querySelector(".answer5")

q1.addEventListener("click", () => { a1.classList.toggle("hide"); q1.parentElement.classList.toggle("bold") })
q2.addEventListener("click", () => { a2.classList.toggle("hide"); q2.parentElement.classList.toggle("bold") })
q3.addEventListener("click", () => { a3.classList.toggle("hide"); q3.parentElement.classList.toggle("bold") })
q4.addEventListener("click", () => { a4.classList.toggle("hide"); q4.parentElement.classList.toggle("bold") })
q5.addEventListener("click", () => { a5.classList.toggle("hide"); q5.parentElement.classList.toggle("bold") })